### PR TITLE
refactor(loaders): remove some warnings 

### PR DESCRIPTION
**Pull request by santimirandarp**
* refactor some regex
* replaced `any` types in a few loaders

### CODE REVIEW

**Comment by lpatiny** [comment]
@targos an idea why this PR does not have a preview ?

**Comment by lpatiny** [comment]
@santimirandarp thanks for the improvements. Indeed my code to split label / units was dating from another century.

I still changed it a little bit to reach a code that I find more readible

https://github.com/zakodium-oss/analysis-ui-components/pull/318/commits/cadd57b8e76127f1e4549c1b45e9482766b1efed

**Comment by targos** [comment]
> @targos an idea why this PR does not have a preview ?

Peviews don't work with branches from forks.

**Comment by santimirandarp** [comment]
> I still changed it a little bit to reach a code that I find more readible

Nice change

**Pull request merged**
