### PR TITLE
fix: side panel not initially closed

### PR DESCRIPTION
**Pull request by hamed-musallam**

### CODE REVIEW

**Comment by hamed-musallam** [comment]
@targos 

can you accept and merge this PR?

**Comment by hamed-musallam** [comment]
@targos 

can you show me what you mean?

**Comment by targos** [comment]
For example:

```
fix: keep side panel closed when initialClosed is passed

Closes: https://github.com/zakodium-oss/analysis-ui-components/issues/175
```

**Comment by hamed-musallam** [comment]
@targos 

sorry for this question, what is the problem with this commit message
```
fix: side panel not initially closed
close #175
```

**Comment by targos** [comment]
Your initial commit message doesn't contain the "close #175". It's technically OK for GitHub to write it like that but we try to comply to the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/). In particular here:
- The commit description must be a summary of the changes (=what the commit does, not what it fixes)
- Footers (like `Close:`, `Closes:`, `Fixes:` etc) need a colon to be in the git trailer format. They also need to be separated from the rest of the message by an empty line

**Pull request merged**
