### PR TITLE
feat: use smaller base font size in components

### PR DESCRIPTION
**Pull request by stropitek**

### CODE REVIEW

**Comment by stropitek** [comment]
@lpatiny @targos 

What do you think of the new size? It mainly affects Tabs, Accordion, and anything with tables

I wanted to use a relatively small base size (12px) since generally the UI will have to be very compact.

**Comment by stropitek** [comment]
The size in App is broken, you can just look at the storybook for now

**Comment by stropitek** [comment]
Fixed the issue in App

**Comment by targos** [comment]
I don't like the smaller icons.

**Comment by stropitek** [comment]
> I don't like the smaller icons

I agree, I did not notice them before. Changed that, but they are still slightly smaller than before.

**Review by targos — APPROVED** [review]

**Comment by lpatiny** [comment]
Nice improvement ! For scientific applications in which we need soo many options it is better to have this compact design (I know I have new glasses ;).

**Pull request merged**
