### PR TITLE
feat:  Render components from layout object

### PR DESCRIPTION
**Pull request by redhaam**
This PR addresses the issues : 
-  Revert RootLayout and add LayoutManager component #110 
- Allow to add custom component from string #108 
- Add id to each component if it doesn't exist #112

### CODE REVIEW

**Comment by lpatiny** [comment]
@redhaam Could you resolve the merge conflicts ? When creating a new branch please take care to go back the main branch, `git pull` and then create the new branch.

**Comment by targos** [comment]
The changes in package-lock.json are not normal. Make sure you are using at lease Node.js 16.14.0, or the Volta version manager.

**Comment by lpatiny** [comment]
@redhaam I removed package-lock.json and node-modules and reinstalled everything ( `npm i `).

This solved I think the big diff in package-lock.json problem.

However there is a new error due to dependencies update. Please could you have a look ?

To be sure you could also on your computer make `rm -rf node_modules` and `npm i` after pulling my change.

**Comment by targos** [comment]
You reintroduced the package-lock change. Please have a look at my comment here: https://github.com/cheminfo/analysis-ui-components/pull/114#issuecomment-1067665567

**Comment by targos** [comment]
Also, please do not make changes in merge commits other than to fix conflicts.

**Comment by lpatiny** [comment]
@hamed-musallam Could you take over this PR ?

**Comment by targos** [comment]
Fixed and merged in https://github.com/zakodium-oss/analysis-ui-components/commit/c82980ce7e6a6f16ff00dda9734b730a8e98cd16

**Pull request closed without merging**
