### PR TITLE
feat: react color picker

### PR DESCRIPTION
**Pull request by hamed-musallam**
we still need to move the js to ts and refactor the whole components, this PR is just to approve that the clone version of the package  is working after i remove the classes and use the functional component code base

### CODE REVIEW

**Comment by hamed-musallam** [comment]
@targos 

it needs too many changes to be in a good shape to be included in our package, I will start moving part by part from js to ts, currently, i replaced the class component with the functional component and be sure that the component work as before

**Comment by hamed-musallam** [comment]
> @hamed-musallam ok. Just try to rebase your PR on the main branch to remove the commits that are already there.

done

**Comment by targos** [comment]
> > @hamed-musallam ok. Just try to rebase your PR on the main branch to remove the commits that are already there.
> 
> done

There is still https://github.com/zakodium-oss/analysis-ui-components/pull/125/commits/800f783b1b80db7378c92ae042bf43eca88515cf to be removed

**Comment by hamed-musallam** [comment]
@targos 

i removed reactcss and replace it with inline style, can you check the component and see if we need more changes?

**Comment by lpatiny** [comment]
Should the package not expose this ColorPicker ?

Should the component itself not be called ColorPicker ?

**Comment by targos** [comment]
Yes, the component should be called ColorPicker. And please fix the merge conflict.

**Comment by targos** [comment]
Also, please rename the `colorPicker` folder to `color-picker` and put the original license file from react-color inside it.

**Comment by targos** [comment]
@hamed-musallam I made a few fixes on the types and some cleanup. Is it ready from your PoV?

**Comment by hamed-musallam** [comment]
@targos 
yes, it is ready, unless you need more changes?

**Pull request merged**
